POST http://localhost:3333/users HTTP/1.1
content-type: application/json

{    
    "name":" Alexandre Santos ",
     "email":" alexandre@growdev.com.br",
    "username": "Alexandy",
    "password": "12345",
     "avatar":"cbxajkvbkdjwvbkwv"
}