POST http://localhost:3333/users HTTP/1.1
content-type: application/json

{    
   "name":"Leonardo",
   "email":"leonardo@hotmail.com.br",
   "username": "leo",
   "password": "12345",
   "avatar":""
}