POST http://localhost:3333/tweets HTTP/1.1
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUwMTE2NjMxLTk5NTctNDMwOS1iOTI5LWJiNWIzMTUzOGYzMiIsIm5hbWUiOiIgUGlldHJvIEJpbGlhdmEgIiwiZW1haWwiOiIgcGlldHJvQGdyb3dkZXYuY29tLmJyIiwidXNlcm5hbWUiOiJQaWV0cm8iLCJhdmF0YXIiOiIiLCJlbmFibGUiOnRydWUsImlhdCI6MTcwNTY3MzI4Mn0.KdM7CauCOqOYH6hmJEsbYM8j9o3F8IBHSeKn2PLrO1A

{
   "content":"meu primeiro tweet"
}
