POST http://localhost:3333/tweets HTTP/1.1
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM0MzViY2I3LTk4M2UtNDRmNi1iYWRhLTRmYTQ5MGE1YzE4ZSIsIm5hbWUiOiJMZW9uYXJkbyIsImVtYWlsIjoibGVvbmFyZG9AaG90bWFpbC5jb20uYnIiLCJ1c2VybmFtZSI6ImxlbyIsImF2YXRhciI6IiIsImVuYWJsZSI6dHJ1ZSwiaWF0IjoxNzA2MTMyNjg5fQ.qjXmlyefdLsy71qRxsdfZgJ0xvA9_hYVIETGw6oIet4

{
   "content":"Primeiro tweet do Leo"
}
