POST http://localhost:3333/replies HTTP/1.1
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE1NGZlN2ZjLTMwYzYtNDhiNy1iNDg2LTk0MmMwZTFhMWQ3MiIsIm5hbWUiOiIgQWxleGFuZHJlIFNhbnRvcyAiLCJlbWFpbCI6IiBBbGV4YW5kcmVAZ3Jvd2Rldi5jb20uYnIiLCJ1c2VybmFtZSI6IkFsZXhhbmRyZSIsImF2YXRhciI6IiIsImVuYWJsZSI6dHJ1ZSwiaWF0IjoxNzA1NzA3MjE5fQ.avrbcpOub6WIOT9CceFxmqQssTKdndP-I7glbG-_sK0

{
   "idTweetBase":"c1e0a81a-bd39-4e72-8c63-f9b83390ea2d",
   "content":"concordo com vc! "
}


 

