PUT http://localhost:3333/replie/cc73e882-266d-4042-91e0-4d1955f9fe8e HTTP/1.1
content-type: application/json
Authorization:403bce88-2ffd-4d3f-b2db-21ca3ce45879

{
    "idUser":"d61d7dec-fcc1-461a-83f7-b4ba9263a9d4",
       "content":"troquei o content"
  
} 