GET  http://localhost:3333/follower HTTP/1.1
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlkNmE0N2FiLTA5Y2QtNGU2Mi04MmIwLWNmMDA3ZDc5ZjhkZiIsIm5hbWUiOiIgUGlldHJvIEJpbGlhdmEgIiwiZW1haWwiOiIgcGlldHJvQGdyb3dkZXYuY29tLmJyIiwidXNlcm5hbWUiOiJQaWV0cm8iLCJhdmF0YXIiOiIiLCJlbmFibGUiOnRydWUsImlhdCI6MTcwNTcyMjM0N30.VlL4ECAvt--5RdMBoGxJQAcTF7W8GaSrc6t2bFxam0g


