GET http://localhost:3333/auth/logout HTTP/1.1
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc4NzZiN2YzLTc3YjMtNDM5MS1iZTgwLWFhNGE5YjJhMWE2OCIsIm5hbWUiOiJKb2FvIFBlZHJvIiwiZW1haWwiOiJqb2FvQGhvdG1haWwuY29tLmJyIiwidXNlcm5hbWUiOiJqb2FvemluaG8iLCJhdmF0YXIiOiIiLCJlbmFibGUiOnRydWUsImlhdCI6MTcwNjEzMjUxOH0.Ji0ZmsUl4O3zhYoaMy3LsaPc3L8UgJqoeva8yaDoUtU
