GET http://localhost:3333/auth/logout HTTP/1.1
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUwMTE2NjMxLTk5NTctNDMwOS1iOTI5LWJiNWIzMTUzOGYzMiIsIm5hbWUiOiIgUGlldHJvIEJpbGlhdmEgIiwiZW1haWwiOiIgcGlldHJvQGdyb3dkZXYuY29tLmJyIiwidXNlcm5hbWUiOiJQaWV0cm8iLCJhdmF0YXIiOiIiLCJlbmFibGUiOnRydWUsImlhdCI6MTcwNTY3ODE4OX0.colYq288iG9BdyyZiYPkr19DibJtBgZ661nbH7bPDYs
